### ISSUE TITLE
Interact v0.3.1 stalls in Jnotebook

### ISSUE THREAD

**Issue by tawheeler** [JuliaLang/Interact.jl#101]
Interact started infinitely stalling in my jnotebooks.

The following works perfectly in the terminal:

```julia
julia> using Interact
julia> @manipulate for i in 1 : 2
           println(i)
       end
Interact.Slider{Int64}(Signal{Int64}(1, nactions=0),"i",1,1:2,"d",true)
1
Signal{Void}(nothing, nactions=0)
```

Running the same code in a new Jnotebook causes it to hang without producing any output.

I am not sure how to debug this. Is there a log or something I can check for where it is getting caught?

I am using Julia 0.4, have Interact v0.3.1, and am running a jnotebook in Chrome on Ubuntu.
It works fine with v0.3.0.

**Comment by shashi** [comment]
what is Jnotebook? Jupyter Notebook?
could you try the new instructions in https://github.com/JuliaLang/Interact.jl#troubleshooting ?

**Comment by tawheeler** [comment]
Thanks!
I had to install ipywigets and the enable the extension.
