### ISSUE TITLE
manipulate just returns last frame in Jupyter 4.0.6?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Interact.jl#102]
I just tried a simple `@manipulate` example with Julia 0.4.6 in IJulia with Jupyter 4.0.6, Interact `master`, and IJulia 1.1.10.  Rather than give me a widget, it just gave me the final output:
![image](https://cloud.githubusercontent.com/assets/2913679/17107576/d9b025ea-525d-11e6-8d33-0a8873d77087.png)
Should I be using a different version of Interact?

**Comment by shashi** [comment]
Did `Pkg.free("Interact")` help? You might want to try a new notebook once you do that. In general the master branch works for `ipywidgets` > 5.x, while the release works for 4.x...

**Comment by stevengj** [comment]
Perfect, thanks!
