### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/Interact.jl#107]
On 0.5rc3, widgets seem to work only with the master version. If so, could you tag a new version please?

**Comment by shashi** [comment]
`master` is supporting ipywidgets 5 + there is an `ipywidgets-4` branch where I'm keeping things working on `ipywidgets 4.x`, both should work on Julia 0.4 and 0.5.

**Comment by shashi** [comment]
I think it's time to tag master and make `ipywidgets 5.x` first-class. I'll also try to make a build script which tries to install this version of `ipywdigets`.
