### ISSUE TITLE
Toggle/Radio button choice does not change for functional values

### ISSUE THREAD

**Issue by mobius-eng** [JuliaLang/Interact.jl#109]
Example:

```julia
@manipulate for s = 1:100, b = Dict("+" => +, "-" => -), c = Dict("F" => 10, "G" => 100)
    (s, b, c)
end
```

Values of `s` and `c` will show the change if corresponding widgets are manipulated, but changing the value of `b` shows no effect.

SysInfo: Julia 0.5v-rc3, master branch of Interact and Reactive.

**Comment by mobius-eng** [comment]
Addition: wrapping the functional value in some type works:

```julia
type MyFunction
    f
end

@manipulate for s = 1:100, b = Dict("+" => MyFunction(+), "-" => MyFunction(-)), c = Dict("F" => 10, "G" => 100)
    b.f(s,c)
end
```

**Comment by jverzani** [comment]
This seems to show up in the example in the README, though I can't double check. With v0.5, the signal is parameterized by `Base.#sin` not `Function` and so, `Base.#cos` is not a valid value.
