### ISSUE TITLE
No label for slider initialised with `slider(1:10, value=1)`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/Interact.jl#112]
With master of `Interact`, I see no label for the slider when initialising a slider with `slider(1:10, value=1)`. I do see a label when just using `@manipulate for i in 1:10`.

``` julia
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by dpsanders** [comment]
<img width="487" alt="screen shot 2016-10-03 at 11 37 06 pm" src="https://cloud.githubusercontent.com/assets/191822/19055039/557c54aa-89c2-11e6-9a31-ed724073849e.png">

**Comment by shashi** [comment]
This was always the case iirc, `slider(1:10, value=2, label="my label")` should do it.
