### ISSUE TITLE
Embedding @manipulate commands?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Interact.jl#114]
If have a case with two parameters, e.g.:

``` julia
@manipulate for k=1:100,j=1:100
    g=myfunction(k)  # expensive function that depends only on k
    f=anotherfunction(g,j)    # cheap function that reuses g
end
```

It would be nice to have the `j` slider responsive, even when the `k` slider is less so.  So I'd want to do something like:

``` julia
@manipulate for k=1:100
    g=myfunction(k)  # expensive function that depends only on k
    @manipulate for j=1:100
        f=anotherfunction(g,j)    # cheap function that reuses g
    end
end
```

Is this possible?

**Comment by dlfivefifty** [comment]
Or rather, I should say, the code I used is not working so is there an alternative that does?

**Comment by JobJob** [comment]
I think this is what you want:

```
k = slider(1:100; label="k")
j = slider(1:100; label="j")
g = map(myfunction, signal(k)) # g is a signal whose value is myfunction(k)
f = map(anotherfunction, signal(g), signal(j)) # f is a signal whose value is anotherfunction(g,j)
map(display, [k,j]) #display widgets
map(display, [g,f]) #display results (that will update when you move the sliders);
```

**Comment by dlfivefifty** [comment]
unfortunately that didn't work for me.

**Comment by JobJob** [comment]
Oh, can you provide a code snippet, error message, or explain in more detail what didn't work?

This works for me:
```
using Interact

myfunction(k) = begin 
    zeros(Int(1e9)) #takes a few secs on my machine
    2k
end
anotherfunction(g,j) = g*j
k = slider(1:100; label="k")
j = slider(1:100; label="j")
g = map(myfunction, signal(k)) # g is a signal whose value is myfunction(k)
f = map(anotherfunction, g, signal(j)) # f is a signal whose value is anotherfunction(g,j)
map(display, [k,j]) #display widgets
map(display, [g,f]) #display results;
```
As in, after moving slider `j`, `f` updates quickly, but if I move slider `k`, the results take a few secs to update.

**Comment by dlfivefifty** [comment]
Hmm, your example works for me but the following doesn't (this is a simplification, the actual case would replace `f(0.1,0.2)` with a plot):

```julia
k = slider(-100.:.1:100.; label="k")
x₀ = slider(-2.:0.1:2.; label="x₀")
y₀ = slider(-2.:0.1:2.; label="y₀")

QR = map(k->qrfact([B;Δ+k*I]), signal(k))
f = map((x0,y0)->((x,y)->exp(-(x-x0)^2-(y-y0)^2)), signal(x₀), signal(y₀)) 
p = map(f->f(0.1,0.2),signal(f))

map(display, [k,x₀,y₀]) #display widgets
map(display, p) #display results;
```

**Comment by JobJob** [comment]
Change the last line to `display(p)` or `map(display, [p])`

**Comment by dlfivefifty** [comment]
Ah, I see, I was confusing `map` for signals with `map` for lists.  Thanks!  

FYI Here's my code that plots the solution to Helmholtz, where the it's fast for moving x_0 and y_0:

``julia
using ApproxFun, Interact, Plots
plotly()

d=Interval()^2
B=Dirichlet(d)
Δ=Laplacian(d)

k = slider(-100.:.1:100.; label="k")
x₀ = slider(-2.:0.1:2.; label="x₀")
y₀ = slider(-2.:0.1:2.; label="y₀")

QR = map(k->qrfact([B;Δ+k*I]),signal(k))
f = map((x0,y0)->Fun((x,y)->exp(-(x-x0)^2-(y-y0)^2)), signal(x₀), signal(y₀)) 
u = map((QR,f)->linsolve(QR,[0.0;f];tolerance=1E-4),QR,f)

map(display, [k,x₀,y₀]) #display widgets
display(map(contour,u)) #display results;
```

**Comment by JobJob** [comment]
Nice. Yep, easily confused.

Btw was curious to run your example but I get `UndefVarError: Dirichlet not defined`

**Comment by dlfivefifty** [comment]
Pkg.checkout(“ApproxFun”,”development”)

**Comment by JobJob** [comment]
Nice, cheers.
