### ISSUE TITLE
compatability with julia 0.5

### ISSUE THREAD

**Issue by jingpengwu** [JuliaLang/Interact.jl#116]
the plots do not have interactive bar. Might caused by the warning message.

![image](https://cloud.githubusercontent.com/assets/7651573/19819031/abc8539c-9d20-11e6-9858-ff86c4ec5a66.png)

**Comment by shashi** [comment]
Do other examples work?

**Comment by jingpengwu** [comment]
unfortunately, I tried a few, they all do not work.

**Comment by shashi** [comment]
It seems your ipywidgets version mismatches what Interact supports. See Troubleshooting section in the README to try and fix this...

**Comment by jingpengwu** [comment]
Sorry, did not notice the troubleshooting section... thanks for your kind help! close here.
