### ISSUE TITLE
Bug in interact.jl with @manipulate in Jupyter

### ISSUE THREAD

**Issue by CorbinFoucart** [JuliaLang/Interact.jl#120]
I am finding that the manipulate macro is behaving unexpectedly (not allowing manipulation, copying results of manipulation into subsequent cells where the manipulate macro is used again) in a way that I believe is buggy. I have met with @dpsanders to discuss; he performed what amounted to a fresh install of Julia on my machine. Nonetheless, we were unable to find a resolution. I have attached an example notebook as well as the data files which it reads.

[interact_bug_report.zip](https://github.com/JuliaLang/Interact.jl/files/581426/interact_bug_report.zip)

OS X El Capitan, Version 10.11.6

**Comment by JobJob** [comment]
Try changing `PyPlot.matshow(data)` to `PyPlot.matshow(data; fignum=0)`, without that I believe a new figure is created for each call to matshow, and the old one doesn't get updated.
