### ISSUE TITLE
siganl of widgets doesn't update

### ISSUE THREAD

**Issue by babaq** [JuliaLang/Interact.jl#121]
```julia
using Interact
eb=togglebuttons([1,2,3])
display(eb)
uuid=[[0,1],[0,1,2],[0,2]]
ub = map(x->togglebuttons(uuid[x]),eb.signal)
```

above code give this in jupyter

![image](https://cloud.githubusercontent.com/assets/92771/20204931/0d588f60-a789-11e6-8f3e-b9db58898cdf.png)

the second togglebuttons is supposed to update to 0,1,2 when first is 2.

couldn't get it working on both ubuntu and windows10, in julia 0.5, master branch of Interact and Reactive

**Comment by JobJob** [comment]
Dup of #47, will restart discussion there.

**Comment by JobJob** [comment]
This should be working on latest master - it also requires IJulia master.
```
Pkg.checkout("IJulia")
Pkg.checkout("Interact")
```
