### ISSUE TITLE
Output doesn't update

### ISSUE THREAD

**Issue by tbreloff** [JuliaLang/Interact.jl#124]
I was just testing this out with Plots.  It doesn't crash, which is an improvement!  However it also doesn't update (which sort of defeats the purpose ;)

Just doing a simple test gave me initial output as expected, but clicking buttons/sliders/etc did not change the output:

```julia
using Plots, Interact
@manipulate for i=[5,20]
    plot(rand(10))
end
```

I made this simple change to https://github.com/JuliaLang/Interact.jl/blob/master/src/IJulia/setup.jl#L95-L97:

```julia
const __i = Ref(0)
function IJulia.display_dict(x::Signal)
    __i[] += 1
    @show __i[]
    IJulia.display_dict(value(x))
end
```

And confirmed that this method doesn't seem to get called after the initial setup.

Any idea what's going on?

**Comment by JobJob** [comment]
Which Plots backend?
Tagged versions of Interact, Reactive, Plots or master?

This is working for me with PlotlyJS backend and a couple of different combinations of master/tagged, as in the plot updates fine when you click the buttons.

**Comment by tbreloff** [comment]
Interesting. I tried with pyplot and gr. What commits are you on?

**Comment by JobJob** [comment]
Not at comp right now, sorry, but Pyplot needs special treatment to work with interact, see the example notebook 3

**Comment by JobJob** [comment]
gr, pyplot and plotly all work for me with tagged IJulia, Interact, Reactive and Plots.
```
using Plots, Interact
# gr()
pyplot()
...
```

You're in IJulia right? Do you have any errors in the js console? In the IJulia backend?

Your Jupyer and ipywidgets versions are good? https://github.com/JuliaLang/Interact.jl#ipywidgets-version.

**Comment by tbreloff** [comment]
I did a `Pkg.free("Interact")` and it's working!  Any idea what might have changed since the last tag?

**Comment by JobJob** [comment]
Oh yeah, there was change in IJulia that is required for current Interact master to work. Checking out IJulia master should sort it out. Need to fix up the REQUIRE. Thanks.

**Comment by JobJob** [comment]
Closing this, will leave #125 open instead until a release is tagged because it's a bit clearer and more succinct if others run into the problem.
