### ISSUE TITLE
Using Interact in a Notebook deployed on Binder

### ISSUE THREAD

**Issue by Ward9250** [JuliaLang/Interact.jl#134]
Hi,

I'm trying to set up a Jupyter notebook that runs using Binder here: [![Binder](http://mybinder.org/badge.svg)](http://mybinder.org:/repo/ward9250/speeddate_binder)

At the moment it's a simple notebook, it loads Reactive and then Interactive, and then I create a slider, but nothing appears in the output of the cell, no slider widget. I'm hoping someone know why and can assist me with this. How I've set this up is in a Dockerfile in the repo [here](https://github.com/Ward9250/SpeedDate_Binder/tree/master).

Essentially the dockerfile is based on the basic Binder container offered by the folks at Binder, but with julia and IJulia installed to provide the additional kernel.

Thanks,
Ben.

**Comment by Ward9250** [comment]
I worked out this is because Binder uses ipywidgets4 and an older jupyter version. I worked around the problem with Binder rather than checkout the ipywidgets4 branch.

**Comment by JobJob** [comment]
This Binder looks interesting. What was the workaround in the end?
Do you have a dockerfile that has Julia and IJulia installed and works with interact?

**Comment by Ward9250** [comment]
I did, and it was working swell, but for some reason it's not so now - nothing to do with julia or IJulia or anything as far as I can see though. I'll post the link here when I have it up and running again.

**Comment by JobJob** [comment]
Ok great, thanks.

**Comment by Ward9250** [comment]
It's also worth keeping in mind everware, which is a similar project by cern: https://github.com/everware
