### ISSUE TITLE
Support side-effects inside @manipulate / support container widgets

### ISSUE THREAD

**Issue by shashi** [JuliaLang/Interact.jl#41]
``` julia
@manipulate for i=1:10
    println(i)
end
```

does not work, leading to confused users (#40, and #26). One possible fix:

Transform manipulate blocks so that they push a display to the stack, and pop it at the end. Then take everything that got printed _and_ the value of the last expression and push them to the front-end. This will require implementing some kind of containers so that values of different mime types can be displayed in the same cell output.

Second possible fix:

Since the only use of println / display is to display multiple things as a result of the same `@manipulate` block, it could be OK to just somehow implement containers and not care about side effects.

**Comment by shashi** [comment]
this is good detective work! Thanks!

It is definitely useful to have this.

However, it would probably be nice if printing would overwrite previously shown output...
![image](https://cloud.githubusercontent.com/assets/25916/20151911/e83cab3a-a670-11e6-82c8-6df94fdbe4c1.png)

See what I mean?

I'm pretty sure this is going to be tricky, but I'd wager it's possible at least inside `@manipulate`.

**Comment by JobJob** [comment]
Yeah. Agree that it would be tricky : ) Might be more trouble than it's worth.

In the meantime though, it probably makes sense that at least the above behaviour works, because I think that's what most people would expect. 

Maybe you can keep this issue open (or rename it) but merge the PR, if/when the IJulia one is accepted.

**Comment by JobJob** [comment]
The other big thing is that without the change in the PR errors are silently dropped:
```
@manipulate for i=1:10
    i==4 && error("invisible problem?")
    i
end
```
---
Also, regarding "displaying multiple things as a result of the same @manipulate block", I had this `splitsig` function in my own libs, adapted it slightly to work when signal types change, and this works pretty well, basically if the last line of the `@manipulate` block is a tuple, it creates a signal for each element in the tuple, and displays those:
```
using Interact

"""split a Signal{Tuple} into a Tuple{Vararg{Signal}}"""
splitsig(tplsig) = ([map(sigs->sigs[i], tplsig; typ=Any) for 
    i in 1:length(tplsig.value)]...)
tuplizesig(sig::Signal) = begin
    T = typeof(value(sig))
    T<:Tuple ? splitsig(sig) : (sig,)
end

Interact.map_block(block, symbols) = begin
    lambda = Expr(:(->), Expr(:tuple, symbols...),
                  block)
    :(map(display,
        tuplizesig(
    preserve(map($lambda, $(map(s->:(signal($s)), symbols)...); typ=Any))
        )
    ); nothing)
end
```

These two and the `error` one above are the only test cases I have looked at:
```
@manipulate for i=1:10
    i*2, "$i"
end
```
```
using TestImages
ims = ["mandrill", 
    "cameraman", 
    "jetplane"]

@manipulate for i=1:length(ims)
    "image $i", testimage(ims[i])
end;
```

One small issue is if you actually want to display a tuple you have to do something like this:
```
@manipulate for i=1:10
    i==4 && error("asdf")
    ((i,i+1),)
end
```
