### ISSUE TITLE
Plain text output widget

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Interact.jl#43]
Does interact have an output widget for just plain text? I didn't see it in widgets.jl. Currently, I'm just returning a string, but that's not as nice because it `show`s rather than `print`s.

**Comment by shashi** [comment]
Okay, I understand the issue now. You want the quotes to go away and the text to not be monospaced. @stevengj does `Text(string)` escape HTML special characters like `<` and `>`?

**Comment by stevengj** [comment]
`Text` outputs as `text/plain`, and therefore it need not do any escaping.
