### ISSUE TITLE
Interact and IPython 3.0-dev

### ISSUE THREAD

**Issue by awellis** [JuliaLang/Interact.jl#44]
Is Interact known not to work with ipython 3.0-dev?
the following example runs on ipython  2.3, but does not produce any output using ipython 3.0-dev:

``` julia
using Interact, Gadfly

@manipulate for y in 1:5 
    plot(x -> x^y, -5, 5) 
end
```

**Comment by kersulis** [comment]
More information on this issue:

One of the error messages I see is 

```
"Error: Class WidgetModel not found in registry ↵    at http://localhost:8888/static/base/js/utils.js:722:28↵
```
I went to the file and line mentioned by the error and found this block of js code:

```js
    var load_class = function(class_name, module_name, registry) {
        /**
         * Tries to load a class
         *
         * Tries to load a class from a module using require.js, if a module 
         * is specified, otherwise tries to load a class from the global 
         * registry, if the global registry is provided.
         */
        return new Promise(function(resolve, reject) {

            // Try loading the view module using require.js
            if (module_name) {
                require([module_name], function(module) {
                    if (module[class_name] === undefined) {
                        reject(new Error('Class '+class_name+' not found in module '+module_name));
                    } else {
                        resolve(module[class_name]);
                    }
                }, reject);
            } else {
                if (registry && registry[class_name]) {
                    resolve(registry[class_name]);
                } else {
                    reject(new Error('Class '+class_name+' not found in registry '));
                }
            }
        });
    };
```
The error is saying that the `WidgetModel` class is not in the global registry. The js code responsible for registering `WidgetModel` is line 390 of `IPython/html/static/widgets/js/widget.js`:

```js
widgetmanager.WidgetManager.register_widget_model('WidgetModel', WidgetModel);
```
Interact works on [JuliaBox](juliabox.org), and the above line of code has the same path (but is line 270 instead of 390 because of all the IPython-dev changes). Perhaps worthy of note is that `utils.js

**Comment by lstagner** [comment]
I am having the same issue as well. Since the IPython 3.0 release candidate is now available it might be a good time to fix this.

**Comment by shashi** [comment]
Fixed on master. Please do `Pkg.checkout("Interact")` to get the fixes, since the fixes break Interact for people still using IPython 2.x, I'm going to wait on tagging a new release.

**Comment by stevengj** [comment]
Is there way to get it working for both IPython versions?  We're doing to have to deal with IPython 2 for a while; it would be good to support it for a year at least.

**Comment by shashi** [comment]
@stevengj Oh a year, is it? The simplest would be to allow Interact to figure out the IPython version, is that possible? Then we can sprinkle some if statements and make it work on both.

**Comment by jiahao** [comment]
+1 for IPython 2.x/3.x support
