### ISSUE TITLE
Hidden state in notebooks causing loss of interactivity

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/Interact.jl#50]
Here are two notebooks

https://gist.github.com/jiahao/97c2050d369812a4416f

and

https://github.com/jiahao/ijulia-notebooks-assorted/blob/57ad26fd39ed273abd0d32a301966791219a45c7/Nuclear%20energy%20levels.ipynb

which, as far as I can tell, have identical content. However the Interact widget in the first notebook doesn't work for me, but works in the second notebook, which was created by pasting each cell from the first notebook into a new notebook.

**Comment by shashi** [comment]
I am unable to run the notebooks. The `maximum` function in the last cell results in a "reducing over empty array..." error. If I try to make that go away by returning 0 when the input is empty I get a boundserror at which point I don't know what to change.

I did a diff of the notebooks after removing all the Gadfly svg ids. There is *nothing* different between the two :o

**Comment by shashi** [comment]
Could you try this on master again?

**Comment by JobJob** [comment]
I had some similar issues, which I worked around by clearing all output form the menu (Cell -> All output -> clear) and restarting the kernel

**Comment by shashi** [comment]
I think I have fixed this reasonably. If you run `using Interact` more than once in the same session and the same cell, you lose interactivity *after* you save and reload the page and then try the widgets without restarting the kernel.
