### ISSUE TITLE
Iteract doesn't work in the slideshow mode

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/Interact.jl#53]
Julia Version 0.3.6 (2015-01-08 22:33 UTC)

Interact works fine in IJulia

![works](https://cloud.githubusercontent.com/assets/2822757/6428356/29ad1f36-bf7e-11e4-802b-80ba0556e7e0.png)

But it doesn't work for slides.

The conversion to slides was done with: 
```ipython nbconvert Interact.ipynb --profile=julia --to=slides --post=serve```

![slides](https://cloud.githubusercontent.com/assets/2822757/6428361/78573252-bf7e-11e4-92b1-d493dafea99a.png)

**Comment by shashi** [comment]
It looks like nbconvert converts the notebook into a static form. Can you even run any code?

In the past, I have had luck with the [slideshow extension to IPython](http://nbviewer.ipython.org/github/fperez/nb-slideshow-template/blob/master/install-support.ipynb) which lets you go into slideshow mode from a running notebook. Maybe that can help you. Please reopen this issue if that doesn't work - slideshows with Interact are really cool.
