### ISSUE TITLE
IPython 3 breaks Interact

### ISSUE THREAD

**Issue by berceanu** [JuliaLang/Interact.jl#55]
I just updated IPython to v3 (jupyter 3.0.0-f75fda4) and all my widgets stopped working (nothing is displayed). 
simplest example 
```
using Reactive, Interact
slider(1:5, label="x")
```
--> no output

**Comment by shashi** [comment]
Hey, could you do a `Pkg.checkout("Interact")`? That should fix the problem.

**Comment by IainNZ** [comment]
Yo @shashi , has this been tagged? Can it be tagged?

**Comment by shashi** [comment]
Not without breaking IPython < 3.0 - but it should be possible to have compat with both, going by https://github.com/JuliaLang/Interact.jl/pull/54#issuecomment-77007652 but I haven't done this yet..

**Comment by A-A-G** [comment]
Seems it still only works with ipython 3.0 by using Pkg.checkout("Interact")? What's the difference to Pkg.add("Interact")? Annoying... Took me long to get it running... A hint somewhere would be nice.

**Comment by stevengj** [comment]
@A-A-G, `Pkg.checkout` gets the latest git `master`, whereas `Pkg.add` gets the latest "released" version.  Unfortunately, it seems really hard to have a single version that works with both IPython 2 and IPython 3, so we are a bit stuck on what to release.

**Comment by A-A-G** [comment]
@stevengj Thanks for the explanation. 
Perhaps a hint at readme.md would be nice. Especially as there is described Pkg.add("Interact") along with Jupyter/IPython 3.0 requirement.
