### ISSUE TITLE
@manipulate shows no output: "comm.send is not a function"

### ISSUE THREAD

**Issue by dchem** [JuliaLang/Interact.jl#56]
Problem:
When I use the manipulate feature of Interact, I do not see the output widget or graph:

![screenshot from 2015-03-16 14 12 40](https://cloud.githubusercontent.com/assets/1108367/6676617/9133a43a-cbe6-11e4-8b73-58e883b76f2b.png)

Here's the Firefox's console output
```console
Object { fileName: "http://localhost:8998/static/base/js/utils.js?v=20150316134900", lineNumber: 696, columnNumber: 18, stack: "WrappedError@http://localhost:8998/static/base/js/utils.js?v=20150316134900:696:19
reject/<@http://localhost:8998/static/base/js/utils.js?v=20150316134900:775:33
", message: "Could not open comm", error_stack: Array[2] } utils.js:776:21

Object { fileName: "http://localhost:8998/static/base/js/utils.js?v=20150316134900", lineNumber: 696, columnNumber: 18, stack: "WrappedError@http://localhost:8998/static/base/js/utils.js?v=20150316134900:696:19
reject/<@http://localhost:8998/static/base/js/utils.js?v=20150316134900:775:33
", message: "Could not open comm", error_stack: Array[2] } utils.js:776:21

TypeError: comm.send is not a function jquery.min.js:67:0

```

Here's my package list:
```python
julia> Pkg.installed()
Dict{ASCIIString,VersionNumber} with 44 entries:
  "Interact"          => v"0.1.6"
  "ImmutableArrays"   => v"0.0.6"
  "ZMQ"               => v"0.1.16"
  "ArrayViews"        => v"0.4.9"
  "DataStructures"    => v"0.3.6"
  "Compat"            => v"0.3.3"
  "Calculus"          => v"0.1.6"
  "GZip"              => v"0.2.13"
  "DataFrames"        => v"0.6.1"
  "Showoff"           => v"0.0.3"
  "Distributions"     => v"0.6.5"
  "FixedPointNumbers" => v"0.0.6"
  "SHA"               => v"0.0.3"
  "DualNumbers"       => v"0.1.2"
  "KernelDensity"     => v"0.1.0"
  "Iterators"         => v"0.1.7"
  "Gadfly"            => v"0.3.11"
  "Dates"             => v"0.3.2"
  "Contour"           => v"0.0.6"
  "PDMats"            => v"0.3.1"
  "Optim"             => v"0.4.0"
  "SortingAlgorithms" => v"0.0.4"
  "PyCall"            => v"0.7.3"
  "Color"             => v"0.4.2"
  "Grid"              => v"0.3.7"
  "JSON"              => v"0.4.1"
  "StatsBase"         => v"0.6.12"
  "Hexagons"          => v"0.0.2"
  "IJulia"            => v"0.2.1"
  "Distances"         => v"0.2.0"
  "PyPlot"            => v"1.5.1"
  "Loess"             => v"0.0.3"
  "BinDeps"           => v"0.3.7"
  "Reexport"          => v"0.0.2"
  "Graphics"          => v"0.1.0"
  "URIParser"         => v"0.0.4"
  "NaNMath"           => v"0.0.2"
  "Nettle"            => v"0.1.8"
  "REPLCompletions"   => v"0.0.3"
  "Reactive"          => v"0.1.10"
  "LaTeXStrings"      => v"0.1.2"
  "Compose"           => v"0.3.11"
  "DataArrays"        => v"0.2.11"
  "Codecs"            => v"0.1.3"
```
Thank you.

**Comment by shashi** [comment]
Which version of IPython are you using? If it's >= 3.0, do `Pkg.checkout("Interact")`.

**Comment by dchem** [comment]
I have IPython 3.0, and when I did the ```Pkg.checkout("Interact")``` it said that there isn't anything to update. I did ```Pkg.update()``` and then ```Pkg.update("Gadfly")``` and now the installed version says 0.1.6+

Here's the installed package output:
```python
Dict{ASCIIString,VersionNumber} with 44 entries:
  "Interact"          => v"0.1.6+"
  "ImmutableArrays"   => v"0.0.6"
  "ZMQ"               => v"0.1.16"
  "ArrayViews"        => v"0.4.9"
  ⋮                   => ⋮
```

When I execute the maipulate example script, now the interactable widget shows up, but the graph fails to show:
![screenshot from 2015-03-17 11 28 05](https://cloud.githubusercontent.com/assets/1108367/6694654/e8484980-cc98-11e4-87b5-816511110b29.png)

Here's the output from the ipython when I execute that line:
```
[W 11:21:32.399 NotebookApp] 404 GET /kernelspecs/julia%200.3/logo-64x64.png (127.0.0.1) 2.05ms referer=http://localhost:8998/notebooks/workspace/juliatest/Untitled1.ipynb
```

**Comment by shashi** [comment]
Hmm so to remove the previous Javascript that Interact might have loaded, you need to remove the cell containing the `using ` statements, restart the kernel, reload the page, add the cell back in, and run it again. Note that you need to remove the cell by hitting the cut button and save the notebook, just deleting the text in the cell won't help. Or just start over in a brand new notebook. Did you try this yet?

**Comment by dchem** [comment]
Ok, I have come to a solution.

I did ```Pkg.rm("Gadfly")``` to get rid of weirdness that accumulated. I re-added that package.
Next, I did the same for Interact. After that to get rid of ```comm.send``` error message, I did ```Pkg.checkout("Interact")```.

Thanks for the help.

**Comment by kietdlam** [comment]
Hi, was this issue ever resolved? I am still getting the same error.
