### ISSUE TITLE
Widgets are not shown.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/Interact.jl#59]
julia-users discussion:

* https://groups.google.com/forum/#!topic/julia-users/WizS8priwuA

![](https://files.gitter.im/Ismael-VC/julialang-es/mN7n/Screen-Shot-2015-03-26-at-4.26.25-PM.png)
![](https://files.gitter.im/Ismael-VC/julialang-es/dyGs/Screen-Shot-2015-03-26-at-1.48.01-PM.png)

**Comment by Ismael-VC** [comment]
https://github.com/JuliaLang/Interact.jl/issues/55

**Comment by shashi** [comment]
Closing because it's been talked about before. Pkg.checkout is required on IPython 3.0
