### ISSUE TITLE
Manipulate stopped working with IPython 3.0

### ISSUE THREAD

**Issue by mykelk** [JuliaLang/Interact.jl#60]
I have been using `@manipulate` successfully until I upgraded to IPython 3. The widgets (and plot) do not seem to appear. Here is an example:
![image](https://cloud.githubusercontent.com/assets/6294079/6973587/9ff2de16-d940-11e4-9224-4653b84f9f54.png)
I have this issue with Julia 0.3.6 and 0.3.7 on both Windows and Ubuntu. I'm using conda for Python. I've rebuilt IJulia, and I also tried deleting my .ipython directory and reinstalling. Everything else in IJulia seems to work just fine.

**Comment by jiahao** [comment]
See #54 - you will have to do `Pkg.checkout("Interact")` to get the master version.

**Comment by mykelk** [comment]
Thanks! I got the master of Interact (and Reactive). The widget now shows up, but the plot does not.
![image](https://cloud.githubusercontent.com/assets/6294079/6976277/1e9aba20-d95c-11e4-9c5f-cf35de0a9d4f.png)

**Comment by jiahao** [comment]
Possibly a PyPlot issue now?

**Comment by shashi** [comment]
Could you start in a fresh notebook and try this. There will be stale JS that is hard to get rid of after you do `Pkg.checkout`

**Comment by mykelk** [comment]
Thanks @shashi! A fresh notebook took care of the problem.
