### ISSUE TITLE
Textbox doesn't handle accents.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/Interact.jl#61]
Using JuliaBox:

![accents](https://cloud.githubusercontent.com/assets/4594825/7103183/d956cd74-e058-11e4-930c-50fd06ae54fd.JPG)

**Comment by stevengj** [comment]
@Carreau, is this an issue on the IPython side?

**Comment by Carreau** [comment]
No seem to work on 3.1 (tried on try.jupyter.org) 
![capture d ecran 2015-04-20 a 14 04 29](https://cloud.githubusercontent.com/assets/335567/7240506/413fa190-e766-11e4-868b-8f926f643d4f.png)
