### ISSUE TITLE
Basic examples not working

### ISSUE THREAD

**Issue by izahn** [JuliaLang/Interact.jl#62]
I'm trying to run a simple example like

```
using Interact
using Gadfly
using RDatasets
@manipulate for n=1:25, g = [Geom.line, Geom.point]
   Gadfly.plot(y=rand(n), x=rand(n), g)
end
```
but nothing happens when I run this in IJulia. The little asterisk telling indicating the cell is running appears but never goes away, and no output is generated. I have julia 0.3.8 , Interact 0.16, and ipython 3.1.0. Am I doing something obviously wrong? Any hints on how to debug?

**Comment by shashi** [comment]
For IPython 3.0+ you need to be on `master`. Run `Pkg.checkout("Interact")`

Things are still broken due to some API changes in DataStructures package, I'm fixing this. Will let you know how far I get today.

**Comment by izahn** [comment]
OK thanks. It does work for me after checking out master.
