### ISSUE TITLE
manipulate only displays first control

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Interact.jl#64]
```
@manipulate for j = 0:length(julia_passes), short = Dict(:short => "short",:long => "long"),
        layout = Dict(:neato => "neato", :dot => "dot");

end
```
![screen shot 2015-06-26 at 12 06 38 am](https://cloud.githubusercontent.com/assets/1291671/8370573/93a731cc-1b97-11e5-83ce-c08c9bae245a.png)

**Comment by shashi** [comment]
The bug was that selection widgets were not showing up. Fixed now on master.
