### ISSUE TITLE
Not working with IPython 3.2 and julia 0.3.10

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/Interact.jl#68]
On julia 0.3.10, ipython 3.2, IJulia, React and Interact on master, I am able to get a rendered widget but it appears to not be connected to any React signal.

<img width="576" alt="screen shot 2015-07-06 at 9 44 33 pm" src="https://cloud.githubusercontent.com/assets/1732/8537181/521f7954-2429-11e5-853b-457960eaa0ce.png">

The JavaScript console on Chrome doesn't show any errors other than "logo not found".

**Comment by rohitvarkey** [comment]
Is this still happening? I have the same setup, but it works for me.

**Comment by jiahao** [comment]
@rohitvarkey what versions/commits of React and Interact and IJulia are you on? I'm still trying to find a working combination.

**Comment by jiahao** [comment]
OK I got a working combination.
- Julia 0.3.12
- Interact master
- IJulia 0.2.5
- Reactive 0.2.2
- IPython 3.2.1

**Comment by rohitvarkey** [comment]
@jiahao I have the same except for Julia 0.3.10. 

Also @shashi won't Patchwork also matter if you have it installed? I remember you telling me to use Patchwork master sometime when I had some problem with Interact. Could that have been the reason?

**Comment by alanedelman** [comment]
(wish i had this before class yesterday)
