### ISSUE TITLE
togglebuttons doesn't work

### ISSUE THREAD

**Issue by Ken-B** [JuliaLang/Interact.jl#69]
All standard widgets work, including `dropdown` and `radiobuttons`, but `togglebuttons` does not display anything. 

I've tried
```julia
g=togglebuttons(["Add" => +, "Sub" => -, "Exp" => ^])
display(widget([:on, :off]))
display(widget([:π => float(π), :τ => 2π]))
```

I'm on mac with Julia 0.3.11 and I tried different IPython versions (3.0, 3.1, 3.2.1), different python (2.7, 3.4) and different browsers (Safari, Firefox, Chrome). Also tried on Interact master.

Let me know where I can help to debug. Thanks.

**Comment by juliohm** [comment]
Same here on Linux, Julia 0.4 and Jupyter.

**Comment by Ken-B** [comment]
This now works for me on Julia v0.4 and Jupyter 4 both on my mac and windows. For me the issue can be closed.

**Comment by shashi** [comment]
yay! this is a case of one of those phantom failures made impossible to know about by Promises in the new Jupyter. https://github.com/jdfreder/ipywidgets/commit/6f4613e6c345d274d566f4977cb8b971c2bf520a#commitcomment-13252052
