### ISSUE TITLE
Warning: names(v) is deprecated, use fieldnames(v) instead.

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/Interact.jl#70]
The code to reproduce:

```julia
using Interact

@manipulate for c=checkbox(true)
    nothing
end
```

**Comment by juliohm** [comment]
I would fix this issue myself if I had the time to fork and send a pull request. The modification is so small that I decided to simply open an issue.

**Comment by jiahao** [comment]
No longer an issue on v0.1.6
