### ISSUE TITLE
Change label on slider from manipulate function

### ISSUE THREAD

**Issue by CorySimon** [JuliaLang/Interact.jl#72]
Is there a way to change the label on the variable for the slider here:

    P = linspace(0, 1)
    @manipulate for K = .1:.1:10
    plot(x=P, y=K*P./(1 + K*P), 
         Geom.line, Scale.y_continuous(maxvalue=1))
    end

I want the slider to be named "K [1/bar]" so that it has units.

**Comment by shashi** [comment]
```julia
P = linspace(0, 1)
@manipulate for K = slider(.1:.1:10, label="K [1/bar]")
plot(x=P, y=K*P./(1 + K*P), 
     Geom.line, Scale.y_continuous(maxvalue=1))
end
```

Should do the trick.

**Comment by CorySimon** [comment]
@shashi  Thank you, this works!
