### ISSUE TITLE
Warning in Julia 0.5: Base.FloatingPoint is deprecated, use AbstractFloat instead

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/Interact.jl#86]
>WARNING: Base.FloatingPoint is deprecated, use AbstractFloat instead.
WARNING: Base.FloatingPoint is deprecated, use AbstractFloat instead.
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 in depwarn at deprecated.jl:73
 in call at deprecated.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include_string at loading.jl:266
 in execute_request_0x535c5df2 at /home/julio/.julia/v0.5/IJulia/src/execute_request.jl:177
 in eventloop at /home/julio/.julia/v0.5/IJulia/src/IJulia.jl:141
 in anonymous at task.jl:443
while loading /home/julio/.julia/v0.5/Interact/src/IJulia/statedict.jl, in expression starting on line 1

**Comment by jiahao** [comment]
Do you still see this problem on `master`, i.e. if you do `Pkg.checkout("Interact")`? This problem should have been fixed by #81 and may simply need a new version tagged.

**Comment by juliohm** [comment]
I'll check it soon Jiahao, thanks.

**Comment by juliohm** [comment]
Indeed, this is not an issue on master.
