### ISSUE TITLE
@manipulate not updating until mouseup

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/Interact.jl#87]
On Jupyter 4.0.6 and the latest checkout of Reactive and Interact, Gadfly 0.4.0 and IJulia 1.1.8, `@maniuplate` no longer updates as I move the slider, only when I release the mouse.

**Comment by shashi** [comment]
It looks like some changes to IPython widgets. There should be a knob somewhere to get the previous default.

Also the current master + Reactive master is untested. If it works for you, that's great!

**Comment by dlfivefifty** [comment]
It also doesn't work on the tagged versions.  I changed to master to see if it had been fixed.

**Comment by adityam** [comment]
Any update on this. It appears that `@manipulate` is not working with 0.4.2.

**Comment by adityam** [comment]
Thanks
