### ISSUE TITLE
does not work. :(

### ISSUE THREAD

**Issue by jmarcellopereira** [JuliaLang/Interact.jl#91]
The code below, only show the plot, no show slide or button

```jl
@manipulate for a=0:0.1:2*pi , f = Dict("sin"=>sin, "cos"=>cos)
    Gadfly.plot(b -> f(a+b),0,25)
end
```

**Comment by rohitvarkey** [comment]
Please quote your code to avoid pulling in random people! (Use the ``` syntax in provided by Github) 

This code works on my setup. Could you post some more details regarding yours? Julia version, IJulia and Interact versions and the browser used will be helpful to debug!

**Comment by jmarcellopereira** [comment]
Ok, 

Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Jupyter
Python 3.4.4 |Anaconda 2.3.0 (64-bit)| (default, Jan 11 2016, 13:54:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Chrome
Version 45.0.2454.101 Built on Ubuntu 15.04, running on Ubuntu 16 (64-bit)

![interactive-julia](https://cloud.githubusercontent.com/assets/13703314/13688312/d247d74a-e6ff-11e5-826c-b024df24ea7a.png)

**Comment by dpsanders** [comment]
@jmarcellopereira Could you please report the version of the notebook with `jupyter --version`?

**Comment by jmarcellopereira** [comment]
Hi, i used:
4.0.6

**Comment by dpsanders** [comment]
Did you install Jupyter yourself? You could try following the instructions at [`IJulia.jl`](https://github.com/JuliaLang/IJulia.jl) to use a version of Jupyter that is local to Julia.

**Comment by jmarcellopereira** [comment]
I installed following the tutorial jupyter. all other functions work less to interact

**Comment by dpsanders** [comment]
You could try
```
ENV["PYTHON"] = ""
Pkg.build("PyCall")
Pkg.build("IJulia")
```
This will download a local version of Python and Jupyter for use only by Julia. (This won't affect any other Jupyter installation.)

**Comment by dpsanders** [comment]
Also, your Julia version is somewhat old now. Try downloading the latest generic Linux binary.
You could also then delete (or just change the name of) your `~/.julia` directory and reinstall all your packages (or copy over the `REQUIRE` file and then do `Pkg.resolve()`).

**Comment by jmarcellopereira** [comment]
Hi sanders. 
I'm unlucky. I tried all the steps and does not appear the slide bar. It appears the plot function but does not appear the slide bar.

**Comment by jmarcellopereira** [comment]
Now show the tip:
WARNING: using Interact.select in module Main conflicts with an existing identifier.

**Comment by shashi** [comment]
Which browser are you using? Could you see what's in the developer console in the browser?

**Comment by jmarcellopereira** [comment]
Hi Shashi
I used firefox 45.0.2 for linux.
It happened an interesting thing: I used the code in another notebook and now worked! I did not understand.

**Comment by mgiugliano** [comment]
Hi, same problem here (OSX, Safari browser, my own modified Docker image FROM jupyter/minimal-notebook).

Jupyter with Python 3 does work with widgets (e.g. from ipywidgets import *, IntSlider()).
Jupyter with Julia 0.4.5 does not work with widgets.

Any help is very much appreciated!

Jupyter 4.2.0
Python 3.5.1
GCC 4.4.7
Julia 0.4.5
Interact 0.3.1

**Comment by shashi** [comment]
What's the version of `ipywidgets`.

You can find it out by running
```
import ipywidgets
ipywidgets.__version__
```

In the python that runs the jupyter

**Comment by mgiugliano** [comment]
The version of ipywidgets is 5.1.3 (tnx for the guidance.. I am new to Python/Julia and come from C and Matlab ;-)).

**Comment by shashi** [comment]
Well, 5.1.3 has made some changes, we will be moving to it soon, but it doesn't work yet. In the meanwhile the best way to get Interact working is to use whatever `Pkg.add("IJulia")` pulls in by default.

**Comment by mgiugliano** [comment]
Thanks for your help! I uninstalled the ipywidgets by conda and typed again in Julia: Pkg.add("IJulia"): still no luck: no error is printed but no widget appears.

**Comment by dpsanders** [comment]
Can you try

```
ENV["PYTHON"] = ""
Pkg.build("IJulia")
```
This will install Julia's own, private copy of Jupyter.

**Comment by shashi** [comment]
Yes, if you run what @dpsanders posted, it also happens to install  the correct version of ipywidgets. Thanks @dpsanders!

**Comment by mgiugliano** [comment]
I created a (custom) Docker image to be used with tmpnb (modified from jupyter/minima-notebook), so... given my overall inexperience with Docker/Jupyter/Julia, it is not straightforward to implement your suggestion. I tried it within the Jupyter Julia notebook (and it did not work of course). Maybe knowing the required ipywidgets version could help. I tried to look into the files of this git repository but failed to spot the ipywidgets version.

**Comment by mgiugliano** [comment]
Thanks anyway. That did not solve my issue. Please consider disclosing the version of ipywidgets compatible with (or rather required for) Julia's Interact.

**Comment by shashi** [comment]
Interact works for me with `ipywidgets` 4.1.1, I think anything >= 5.0.0 is not going to work since it has breaking API changes.

**Comment by dpsanders** [comment]
@mgiugliano You should be able to add the commands I wrote at the moment when you create your Docker image, so that you include those versions baked into the image.

On the other hand, I have just tried to use `Interact` with `PyPlot` with no luck...

**Comment by mgiugliano** [comment]
@dpsanders On OSX, your early advice works beautifully: it installs automatically a Python distribution (i.e. Python2, NOT 3) and all the required packages. 

I am however trying to setup a server (TMPNB - see https://github.com/jupyter/tmpnb) but the default docker image uses Python 3. That's the problem I think with Interact, despite downgrading by Conda the ipywidgets.

Following your advice and strategy, I setup my own custom docker image (see attached Docker file): I thus completely avoid an explicit install of Python and install Julia while following your advice. This installs Python 2 and should make "Interact" working as it does on my laptop. 

However I could not (yet) correctly recycle previous TMPNB community's Docker files: they use some script from jupyterhub (based on Python 3) and they won't work with Python 2. 

For the moment it does not work upon invoking the following commands:

# create a bunch of unique keys to identify the workers
export TOKEN=$( head -c 30 /dev/urandom | xxd -p )

# run the proxy, detached
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999

# run the orchestrator, detached, using my own image
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image='docker-julia-notebook' —command="jupyter notebook --NotebookApp.base_url={base_path} --ip=127.0.0.1 --port {port}"
 
[Dockerfile.txt](https://github.com/JuliaLang/Interact.jl/files/273014/Dockerfile.txt)

**Comment by psilva07** [comment]
I'm in the same situation too, the slider does not appear on the plots. As @mgiugliano my `ipywidgets ` version is 5.1.3 and I can't really modify my jupyter version because I'm using it remotely in a server.

**Comment by ViralBShah** [comment]
With the latest jupyter and ipywidgets that I get with pip, this doesn't work.

**Comment by dpsanders** [comment]
I am now having exactly the same problem, even after deleting my .julia directory. No sliders appear. This is with ipywidgets 4.1.1
```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by dpsanders** [comment]
That was with notebook-4.2

**Comment by ViralBShah** [comment]
A lot of people at the workshop I was at today had the same issue. I believe @shashi filed an issue upstream, but we need to perhaps find a fix.

**Comment by SylvainCorlay** [comment]
It is fixed in notebook master. We should release notebook 4.2.1 with the fix soon. @minrk

**Comment by shashi** [comment]
@SylvainCorlay what was the issue?

**Comment by SylvainCorlay** [comment]
Some jquery configuration issue. Fixed in https://github.com/jupyter/notebook/pull/1399

**Comment by shashi** [comment]
Thanks to @SylvainCorlay for the help, I have fixed these issues on the master branch. Do try it out.

**Comment by ViralBShah** [comment]
I am trying on master - but doesn't seem to work for me on the fluid images notebook.

**Comment by ViralBShah** [comment]
However, a simple example works - but all the ones that used manipulate with images are no longer working. The issue may be with the other packages, rather than Interact though.

**Comment by SylvainCorlay** [comment]
Are you exposing the `layout` attribute for laying out widgets?

**Comment by shashi** [comment]
@SylvainCorlay no... I think the problem here is left over js from the old version of Interact has some bad interaction with the new stuff...

@ViralBShah could you try copy-pasting the cells in fluid images in a new notebook?

**Comment by ViralBShah** [comment]
Not sure I understand. Let's do it together tomorrow.

**Comment by mgiugliano** [comment]
After (truly) enjoying *Interact* with IJulia for weeks, yesterday's Pkg.update() broke it. 
The sample code below plots the figure but no slider and no button.

```
using Gadfly
using Interact

@manipulate for ϕ=0:pi/16:4pi, f = Dict(:sin => sin, :cos => cos)
    plot(θ -> f(θ + ϕ), 0, 25)
end
```

The information on my setup below:

```
*Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)

*Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) M-5Y71 CPU @ 1.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

*ipywidgets '4.1.1'
*Interact    0.3.1+  master
*Reactive  0.3.3+  master
*IJulia       1.1.10
```

**Comment by ViralBShah** [comment]
Perhaps a tag is needed.

I wonder how to set up CI for this to make sure that this keeps working. It is such an integral part of the julia ecosystem.

@tkelman

**Comment by tkelman** [comment]
test would be a start, if it had any then we'd notice on pkgeval

**Comment by shashi** [comment]
We have Julia level tests now. But that stuff is usually not the problem. A full test is essentially starting up IJulia, then having some program which runs some interact code -  I am not sure how to go about that.

I'm closing this issue because it now has obsolete content. I have added a "troubleshooting" section to the README which should help people who end up with an unexpected version of ipywidgets.

**Comment by tkelman** [comment]
I believe there are various libraries that let you simulate a browser and mock user-interaction, but I'm not too experienced in that area.

**Comment by marcindulak** [comment]
Sliders are missing also in my setup on CentOS7. This is what I do on a clean CentOS7 in order to install IJulia/Interact https://github.com/marcindulak/vagrant-CaltechDelftX-QuCryptox/blob/master/install.sh
and then run https://github.com/QuCryptoX/Week_0/blob/30ac898da641602c6e9f0958c7c612436ddb78f6/Getting_Started.ipynb

~~~
using Interact

print("n^2 ="); # print the text "n^2 = "
@manipulate for n in 0:10;
    n^2;
end
~~~

This is a part of a Vagrant virtual environment so we have a chance to debug this problem eventually?

**Comment by marcindulak** [comment]
OK, I had pywidgets 5.2.2 and updating to Interact master branch Pkg.checkout("Interact") as stated in https://github.com/JuliaLang/Interact.jl/blob/77cd0eb8721e19314d19ae506cf77b68c14d662e/README.md fixed the problem.
