### ISSUE TITLE
stack plots horizontally and change size

### ISSUE THREAD

**Issue by CorySimon** [JuliaLang/Interact.jl#95]
I can use Gadfly to make two plots and stack them horizontally with `@manipulate`, using the code below.

```Julia
@manipulate for theta = 3.0:0.1:10.0

   y1 = compute_y1(theta)
   y2 = compute_y2(theta)

    myplot_1 = plot(x=x, y=y1, Geom.point)
    myplot_2 = plot(x=x, y=y2, Geom.pont)
    
    hstack(myplot_n, myplot_l)
end
```

However, the plots are squished together because the window is kept at the same size. A fix is to add `draw(SVG(24cm, 8cm), hstack(myplot_1, myplot_2))`, but then a static plot without any interactivity is shown. Is there a way to change the window size in Interact.jl with this `hstack` function?

**Comment by JobJob** [comment]
Does `set_default_plot_size(24cm, 8cm)` before the hstack/plot call help?

**Comment by shashi** [comment]
Yes, `set_default_plot_size` should do it.

how about `draw(SVGJS(24cm, 8cm), hstack(myplot_1, myplot_2))`

**Comment by CorySimon** [comment]
Thank you, `set_default_plot_size` works! The `draw()` command, which I tried before posting this, just results in a static plot for me.

**Comment by shashi** [comment]
> The draw() command, which I tried before posting this
Did you try the `SVGJS` backend?

**Comment by CorySimon** [comment]
@shashi the `draw(SVGJS(24cm, 8cm), hstack(myplot_1, myplot_2))` works too!

**Comment by shashi** [comment]
Can we close this issue?

**Comment by CorySimon** [comment]
@shashi Yes, thank you! This tool is very helpful for my research (exploring how the model solution depends on parameters)!
