### ISSUE TITLE
`using Interact` causes 100% CPU usage forever

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/Interact.jl#96]
Just importing Interact with `using Interact` or `import Interact` causes Julia to spawn a background task which consumes an entire CPU core on my machine, apparently forever. The `import Interact` command returns quickly, but as soon as I've done so, the `julia` process starts consuming 100% CPU, and appears to be stuck that way (it ran for at least an hour until it killed my laptop battery). Julia and the `@manipulate` widgets both work fine despite this. 

I've tried this with the latest tagged release of `Interact` and with the `master` branch, with the same results. I'm running Julia v0.4.5 on OSX:

```
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
± julia -E "Pkg.installed()"                                                           1 ↵  git:(master) 18:07:31
Dict("NaNMath"=>v"0.2.1","Interact"=>v"0.3.1+","ForwardDiff"=>v"0.1.8","PyLCM"=>v"0.0.2","RigidBodyDynamics"=>v"0.0.0-","Quaternions"=>v"0.1.0+","Interpolations"=>v"0.3.5","FixedPointNumbers"=>v"0.1.3","AxisAlgorithms"=>v"0.1.4","Reactive"=>v"0.3.2","Conda"=>v"0.1.9","SHA"=>v"0.1.2","DualNumbers"=>v"0.2.2","Meshing"=>v"0.0.2","PyCall"=>v"1.4.0","Docile"=>v"0.5.23","WoodburyMatrices"=>v"0.1.5","Combinatorics"=>v"0.2.1","FixedSizeArrays"=>v"0.1.0","JSON"=>v"0.5.0","DataStructures"=>v"0.4.4","ColorTypes"=>v"0.2.2","Compat"=>v"0.7.17","IJulia"=>v"1.1.9","Iterators"=>v"0.1.9","ZMQ"=>v"0.3.1","Calculus"=>v"0.1.14","GeometryTypes"=>v"0.1.4","MultiPoly"=>v"0.1.0","Polynomials"=>v"0.0.5","MacroTools"=>v"0.3.0","AffineTransforms"=>v"0.1.4","Dates"=>v"0.4.4","BinDeps"=>v"0.3.21","DrakeVisualizer"=>v"0.0.0-","LCMGL"=>v"0.0.0-","Ratios"=>v"0.0.4","SpatialFields"=>v"0.0.0-","Requires"=>v"0.2.2","Homebrew"=>v"0.2.0","Nettle"=>v"0.2.3","URIParser"=>v"0.1.3")
```

I observe the same behavior on my Ubuntu 14.04 desktop. I also see the issue regardless of whether I'm importing Interact from the julia command line or from a Jupyter notebook. 

Any ideas what might be going on?

**Comment by rdeits** [comment]
This turned out to actually be due to https://github.com/JuliaLang/Reactive.jl/issues/95 . Sorry for the noise.

**Comment by shashi** [comment]
`Pkg.checkout("Reactive")` should fix it for you now. Awaiting merge into METADATA

**Comment by rdeits** [comment]
Yes, that worked, thanks!
