### ISSUE TITLE
Cannot see widgets after upgrading to new ipywidgets and jupter notebook versions

### ISSUE THREAD

**Issue by CorySimon** [JuliaLang/Interact.jl#98]
When I update the Jupyter Notebook to version 4.2.1 and `pip install ipywidgets --upgrade`, the widget (slider bar) does not appear using Interact.jl anymore. How can I troubleshoot this? Thanks.

Ubuntu 14.04, Google Chrome, Julia 0.4.5, `Pkg.update()`'ed.

**Comment by CorySimon** [comment]
As an additional conformation, I just got a new computer, installed everything from scratch, and the problem persists. No widgets are showing.

**Comment by epifanio** [comment]
Same problem here, from the js console I can read:

```
Could not cross validate the widget frontend and backend versions. Error: Timeout while trying to cross validate the widget frontend and backend versions.
    at http://epinux.com:8888/user/epinux/nbextensions/jupyter-js-widgets/extension.js?v=20160613014000:32275:25
```

**Comment by shashi** [comment]
Could you try the master branch of Interact?

**Comment by CorySimon** [comment]
@shashi I switched to the master branch, and the problem persists.

**Comment by shashi** [comment]
Did you try a fresh notebook? There's an issue with running older notebooks...

**Comment by CorySimon** [comment]
@shashi Ah, it works when I try a fresh notebook. i.e. when I create a new Jupyter Notebook and copy and paste the same code into it. Thanks.

**Comment by shashi** [comment]
These things should be much more robust now. I have tagged a new version which works with ipywidgets 5.x. Pleas open new issues if anyone faces any issues!
